### ISSUE TITLE
Initially running causes a lot of 429 errors

### ISSUE THREAD

**Issue by jonas747** [turnage/graw#12]
Heyo, since you're using the default user agent when fetching the token reddit will 429's a lot. Normally i have to retry around 3 times to get it running.

**Comment by turnage** [comment]
What do you mean, the default user agent? You can [define your own](https://github.com/turnage/graw/wiki/agent-files).

**Comment by jonas747** [comment]
When you call PasswordCredentialsToken, the default user agent is used, not the one specified in the agent file.

**Comment by turnage** [comment]
Thank you for reporting! It appears to be fixed on my end; feel free to re-open if you still experience problems.
