### ISSUE TITLE
Use graw in a one-shot script

### ISSUE THREAD

**Issue by robertgzr** [turnage/graw#16]
I'm trying to do something very simple... sending out simple direct messages to a bulk of users.

My problem is that the examples only showcase how to write bots that react to certain events...

The way I see it graw is the most complete reddit api implementation in Go but can I use it for something like this?

Edit:
In Python this would be a 4 line script but I would like to do this in Go because the processing that needs to be done before is already happening there
```Python
import praw

r = praw.Reddit(user_agent='...')
r.login()

r.send_message('user', 'subject', 'subject')
```

**Comment by turnage** [comment]
```
package main

import (
        "fmt"

        "github.com/turnage/graw"
)

type mailer struct{}

func (m *mailer) SetUp() error {
        eng := graw.GetEngine(m)
        err := eng.SendMessage("roxven", "test", "test body")
        eng.Stop()
        return err
}

func main() {
        if err := graw.Run("agent.protobuf", &mailer{}); err != nil {
                fmt.Printf("An error occurred: %v\n", err)
        }
}
```

This isn't the use case I designed graw for but it can certainly accomplish the task. If you have any suggestions for making this easier I'm interested.

**Comment by robertgzr** [comment]
Thanks that does the job.

Maybe you could have a clear API wrapper and a separate package for writing bots like this.

Looks like you already have that wrapper in the `internal` package...  That would make it possible to script reddit like you can do with `PRAW` which is basically what I want here.

**Comment by turnage** [comment]
See the new [reddit package](https://godoc.org/github.com/turnage/graw/reddit)
