### ISSUE TITLE
All comments event stream

### ISSUE THREAD

**Issue by andyleap** [turnage/graw#20]
Is there any way we could set up monitoring for every comment in a subreddit?  I can get the list of all comments at a url like `https://www.reddit.com/r/generalsio/comments.json`

**Comment by turnage** [comment]
Do you have more information about this endpoint? Specifically:

1. How are the endpoint elements sorted; is this a feed of new comments?
2. Visiting that url gives me 24 comments with flat structure; will it always be flat or are there cases where some comments have a reply tree featuring older comments?

**Comment by andyleap** [comment]
from what I've read, it's a feed of all the comments.  I can't say specifically as to if it'll tree, but I'd assume a new comment can't have older replys.

Based on https://github.com/praw-dev/praw/blob/master/praw/models/listing/mixins/subreddit.py#L46, praw seems to be treating it as a listing like posts.  From what I've heard, this is the endpoint that bots like the "quote me" bot use to get all comments, but I'm unsure about that.

**Comment by turnage** [comment]
Right, yes, my mistake; I rather was thinking of any replies at all.

I've looked at a few bigger subreddit's feeds at this endpoint and I think it is safe to assume it works like /new for comments and that there will not be reply trees. It even allows the same sub1+sub2 merging.

I drafted it in [the comments branch](https://github.com/turnage/graw/tree/comments). I'll run it for a few days and decide how to fit it into the API if my understanding holds up.

In the mean time you can use that branch and specify the subreddits from want comments from in  the config's ````SubredditComments```` field, which will connect the new comments to a bot method ````Comment(c *reddit.Comment)````.

**Comment by andyleap** [comment]
Nice!  Users of the bot I'm working on have been requesting the ability to invoke it on urls in any comment in the subreddit, so I think they'll be quite pleased with this!

**Comment by turnage** [comment]
Merged in!
