### ISSUE TITLE
Fetching top/hot/controversial posts

### ISSUE THREAD

**Issue by itsmehemant123** [turnage/graw#25]
Any intention to support fetching posts via the other sort-orders? Or pulling on `/new` was intentional?

**Comment by turnage** [comment]
At least as part of the graw event feed, I don't intend to support other sort orders as they aren't strict. Posts may change orders in top, rising, or hot and then graw might feed them to bots twice. If you want to manually fetch in a different order, you can use the [Scanner interface](https://godoc.org/github.com/turnage/graw/reddit#Scanner) in the `graw/reddit` package e.g.:

```go
harvest, err := bot.Listing("/r/rust/top")
if err != nil {
  fmt.Printf("lol no generics: %v", err)
} else {
  for _, post := harvest.Posts {
    // handle each post
  }
}
```

But be aware you may get duplicate posts and there's not a good way to know when it's appropriate to pull again (at least that I'm know of).

**Comment by itsmehemant123** [comment]
Oh, that makes sense. Thanks!
