### ISSUE TITLE
passing query params to Listing

### ISSUE THREAD

**Issue by guliyevemil1** [turnage/graw#26]
Hey, as far as I can tell, there is no way to pass query params like "t=hour" through the Listing API. The only way that I can see of doing this is to have my own Scanner implementation that does which would have been easier if you had exported your reaper interface and implementation. What would you suggest I do?

**Comment by turnage** [comment]
My API promise reserves the ability to add methods to an interface; if you would like to add one to the Scanner interface to accommodate this I can promptly review & merge. I wouldn't be able to get to this myself for some time.

**Comment by turnage** [comment]
Fixed in #27
