### ISSUE TITLE
Can you add more info around filling out the template?

### ISSUE THREAD

**Issue by bkern** [turnage/graw#3]
I can't quite figure out what is required for 
user_agent: "<platform>:<app ID>:<version string> (by /u/<reddit username>)"

When I created the app it asked if it was web/installed/personal use not sure if that is platform? 

It also doesn't explicitly say if which id is client id but I have to imagine the first id listed under my personal app name is the client id.

**Comment by turnage** [comment]
The user agent placeholder in the template is taken straight from Reddit's api rules. It doesn't need to be formatted strictly, but it must contain information about the author, the title, the version number, and other listed items.

Your app should be a script app. [See here](https://github.com/reddit/reddit/wiki/OAuth2) for details from Reddit's guide. Theoretically it only has access to one account and only you run it.

Your client id is the unlabeled string under your personal app name.

Thanks for opening the issue! I'm sorry I didn't back for so long; I accidentally disabled issue emails at some point.

I will update the wiki with this information and close the issue tonight.

**Comment by turnage** [comment]
Looks like I was wrong about the agent; it does need to be in the format provided in the template.

The [documentation](https://github.com/turnage/graw/wiki) now addresses the things in your issue. Thanks again for the post!
