### ISSUE TITLE
oauth2: token expired and refresh token is not set

### ISSUE THREAD

**Issue by TableMountain** [turnage/graw#32]
Failed to fetch /r/golang:  Get https://oauth.reddit.com/r/golang?before=&limit=100&raw_json=1: oauth2: token expired and refresh token is not set

I'm sure this is some easy mistake I'm making but I can't seem to spot why I keep getting this error. Any help? 
I tried setting up the .agent file with the different examples, no dice. 
my redirect_uri is set to http://127.0.0.1

**Comment by turnage** [comment]
After how long does this happen to your bot?

**Comment by TableMountain** [comment]
immediately. I tried it with someone else's bot credentials and it works fine. I'm wondering if setting my redirect uri to: http://127.0.0.1 is not sufficient or something?

**Comment by TableMountain** [comment]
Not exactly sure why, but I was able to solve this by creating a new app as a personal use script.

**Comment by TableMountain** [comment]
So now I'm able to use it as an installed app too. I'm assuming signing up for the API WAS necessary, but took a while to go into effect (5-10 minutes after signing up).

**Comment by drankou** [comment]
Have similar problem, requests fail after an hour and i don't have refresh token. I didn't find any method implemented in your library to get it. Looks like 
`func (c *Config) Exchange(ctx context.Context, code string, opts ...AuthCodeOption) (*Token, error)`
 method in oath2 library returns *Token with refresh token in it, but there is no method to get "code" from reddit api needed for POST request `grant_type=authorization_code&code=CODE&redirect_uri=URI`
 My app is already signed up for Reddit API usage. Is getting refreshing token implemented in your library?

**Comment by tdakkota** [comment]
Any changes?
