### ISSUE TITLE
Event Stream pauses for hours

### ISSUE THREAD

**Issue by Rukenshia** [turnage/graw#37]
Hello,

I'm using graw for an application that parses all posts and comments of a subreddit (/r/soccerstreams). Additionally, when a post is created it is getting polled for updates every 5 minutes (in order to check comment updates). The graw `Rate` is set to 15 seconds.

It seems like the event stream stops for me for no reason I can think of for ~1 hour and then gives me a batch of events when it resumes. I've set up some monitoring on my application that checks the time when a comment/post was created vs. when my application received it:

![Grafana](https://in.fkn.space/i/2018-04-17_22-03-57_a87f048e94e0e278.png)

You can see that I received a ton of Comment updates at around 18:45 with the difference between the comment being created and the comment being handled in graw higher than 90 seconds.

You can find my code on my GitHub, here are the most relevant links:

* [Bot configuration](https://github.com/Rukenshia/soccerstreams/blob/master/cmd/agent/agent.go#L29)
* [Rate configuration to 15 seconds](https://github.com/Rukenshia/soccerstreams/blob/master/cmd/agent/main.go)
* [Comment handler](https://github.com/Rukenshia/soccerstreams/blob/master/cmd/agent/comment.go#L22)

If you need more information, please do not hesitate to get back here.

As a side note, it seems like graw doesn't log much, I'm trying to set the graw logger but I don't think I've ever seen it output anything.

Thank you for even reading this already!

**Comment by turnage** [comment]
graw requests a new password credentials token every hour (scripts don't get refresh tokens). I did see behavior once in 2015 where the request for a token would appear to be accepted but all responses would  contain an empty JSON body, then on some new token everything would come in at once.

If you're getting empty responses, maybe it's the same. I haven't seen that behavior enough to know what causes it. I would ask in #reddit-dev on freenode.

If you aren't getting responses, maybe I messed up some concurrent logic and graw is stuck.

Unfortunately I won't be able to look into this myself for three weeks, but thank you for opening a detailed issue!

**Comment by Rukenshia** [comment]
Thanks for the quick reply! I'll fork graw and add some debug info for myself when I get the time. If I get anywhere (or nowhere), I will come back to this issue and tell you what I've found out. Thanks!

**Comment by Rukenshia** [comment]
Me again @turnage, I've added some metrics to my fork at https://github.com/Rukenshia/graw and these are the results:

![image](https://user-images.githubusercontent.com/1899599/39088682-a10b75ac-45b6-11e8-91ce-1c77c215a2e2.png)

The stream of requests and the response sizes (32 bytes < response < 256 bytes) _seems_ to be consistent but that measurement really isn't that exact. Next I'll try logging the actual response body, just can't do that properly with Prometheus so I'll try extracting these logs somewhere else.

**Comment by Rukenshia** [comment]
Finally got around to do more logging. It seems like your initial guess is what's happening. The listing keeps returning `[]` children with `before` and `after` always being `null`. at some point it switches back to give proper responses.

**Comment by turnage** [comment]
@stjohnjohnson That explains both the behavior and why certain users see it but not others so I am optimistic.

I removed it the growth; let me know you still experience issues.

**Comment by stjohnjohnson** [comment]
@turnage I believe this has fixed my problems.  Since your change, I haven't noticed any other gaps.  Thank you!
