### ISSUE TITLE
reddit.NewScript uses an http.Client which doesn't specify a timeout

### ISSUE THREAD

**Issue by boreq** [turnage/graw#38]
It is impossible to replace that client or alter it in any way as it is private.

**Comment by turnage** [comment]
I see. Feel free to submit a pr for a default timeout [here](https://github.com/turnage/graw/blob/15877a6c18d60f0ad1336c3d44fb59e95c3e6b40/reddit/agentforwarder.go#L20). The proper way to way to add this to the API, I'm not sure. Probably through [this](https://github.com/turnage/graw/blob/15877a6c18d60f0ad1336c3d44fb59e95c3e6b40/reddit/client.go#L14).

**Comment by Flexicon** [comment]
Should probably be closed since you can pass an `http.Client` through config now.

**Comment by turnage** [comment]
You’re right.
