### ISSUE TITLE
Getting "invalid request :path" when trying to run use type Lurker's Thread.

### ISSUE THREAD

**Issue by haingoctu** [turnage/graw#42]
Trying something simple like,

```
package main

import (
        "fmt"

        "github.com/turnage/graw/reddit"
)

func main() {
        bot, err := reddit.NewBotFromAgentFile("buysale.agent", 0)
        if err != nil {
                fmt.Println("Failed to create bot handle: ", err)
                return
        }

        harvest, err := bot.Thread("https://www.reddit.com/r/hai_test/comments/9qa4wo/buyselltrade_102033/?ref=share&ref_source=link")
        if err != nil {
                fmt.Println("fail: ", err)
                return
        }
		fmt.Println(harvest.Title)
}

```
receiving,

fail:  Get https://oauth.reddit.com/https://www.reddit.com/r/hai_test/comments/9qa4wo/buyselltrade_102033/%3Fref=share&ref_source=link.json?raw_json=1: invalid request :path "https://www.reddit.com/r/hai_test/comments/9qa4wo/buyselltrade_102033/%3Fref=share&ref_source=link.json?raw_json=1"

**Comment by guliyevemil1** [comment]
Have you read the error message? Perhaps try clicking the URLs in the error message?

**Comment by haingoctu** [comment]
Indeed, I did. Then latter is json while the other is forbidden. If you remove the oauth prefix, it will load the json. 

Don't think it's an oauth issue.n anyone reproduce?

**Comment by turnage** [comment]
iirc Thread takes a path to a thread, not a url. It decides internally what
hostname and query parameters to use.

**Comment by haingoctu** [comment]
Thanks for clarifying.
