### ISSUE TITLE
Support for userless authentication

### ISSUE THREAD

**Issue by bogatuadrian** [turnage/graw#45]
[graw](https://github.com/turnage/graw) doesn't seem to support Application Only OAuth (as described in the reddit OAuth [doc](https://github.com/reddit-archive/reddit/wiki/OAuth2#application-only-oauth)) for "read-only" "user-less" access to the reddit API.

This should be made possible by allowing empty username and password in the [`reddit.App`](https://github.com/turnage/graw/blob/15877a6c18d60f0ad1336c3d44fb59e95c3e6b40/reddit/app.go#L7) struct and using [golang.org/x/oauth2/clientcredentials](https://godoc.org/golang.org/x/oauth2/clientcredentials) for 2-legged OAuth authentication in `appClient`'s [authorize](https://github.com/turnage/graw/blob/15877a6c18d60f0ad1336c3d44fb59e95c3e6b40/reddit/appclient.go#L27) method if the `Username` and/or `Password` fields are not provided.

I can make a pull request if you agree this feature should be added. I will probably fork graw anyway because I need this feature for a project.

Thanks

**Comment by turnage** [comment]
I looked at your changes and I would accept a PR if you'd like to share them upstream. The only thing I'd like to add is an error if username or password are set, but not the other. Thank you for opening an issue!

**Comment by bogatuadrian** [comment]
@turnage Is it OK to return the error from the `authorize()` method? I would have liked it to be further up the stack, but I can't find a good place for it (mostly because `configured()` returns a boolean and I don't want to change to many things).

**Comment by bogatuadrian** [comment]
@turnage It could be cleaner and better for testing to refactor `configured() bool` to `validate() error` and return appropriate validation errors. What do you say?

**Comment by turnage** [comment]
Yeah iirc that doesn't change the public API so sounds totally fine.

**Comment by bogatuadrian** [comment]
Yeah, it is un-exported and called only in one place (except for a test).

**Comment by bogatuadrian** [comment]
PR https://github.com/turnage/graw/pull/46 aims at providing the discussed feature.

**Comment by turnage** [comment]
Merged! Thank you for upstreaming your changes!
