### ISSUE TITLE
Getting historic data

### ISSUE THREAD

**Issue by nmiculinic** [turnage/graw#47]
This would probably be a feature request since I'd love the ability to fetch historical data (( e.g. all posts newer than 1 day, or something like that ))

If it's possible doing it with graw I'd like to know how, since don't see it right now.

**Comment by turnage** [comment]
Late response but for the record I think this is possible with [Scanner](https://godoc.org/github.com/turnage/graw/reddit#Scanner). Just check the Reddit API docs for the right keys and values to pass. You can navigate backward through the listing yourself.

There's definitely not a convenient API for this. I'm willing to discuss that with someone if they want to implement it.
