### ISSUE TITLE
oauth2: token expired and refresh token is not set

### ISSUE THREAD

**Issue by monkeydioude** [turnage/graw#52]
Hello everyone,

for 2 weeks now, I have this issue where the token expires after 1 hour (as it is described in the reddit documentation) and the token isn't refreshed.

I'm not sure of what happened.
I don't think something changed, else a release of this package would have been made following the changes.
On my end, the only thing that changed is domain name.
I subscribed to the Reddit API using my secret_id. I also changed the redirect_uri to follow the new domain name (not sure it's of any effect but sometimes things get esoteric).

How does this work inside the package ? I didn't find any code about token refreshing and it used to work perfectly fine before.

I use this cool package for a long time now and I would be glad to make a PR about token refresh if needed.

**Comment by turnage** [comment]
There was recently activity in #32, which is about this as well. The code in this package has not changed, but it is possible there was a change upstream.

Let me merge this into that and re-open it to keep the conversation together.

If you are interested in making that PR and are willing to update or add tests, I would be happy to accept it.

**Comment by monkeydioude** [comment]
I'll try to make things great again on my side and I'll come back to you. How does that sound ?

**Comment by monkeydioude** [comment]
Turns out the way of retrieving the access_token the package use does not allow to use the refresh_token flow and therefore the `golang.org/x/oauth2` package, which is supposed to refresh the token on it's own, can not.

Right now i'm thinking to add a goroutine in the package to make a call to the access_token endpoint similar than the very first one and get a new access_token before it expires. Not entirely sure how the api will like this.

**Comment by monkeydioude** [comment]
Can people passing by updoot this https://www.reddit.com/r/redditdev/comments/dsedeu/change_in_the_grant_typepassword_behavior/

This is not some soft karma hunting :no_good:

**Comment by turnage** [comment]
The Reddit API docs were never clear about this in my opinion.

From the docs:

> Access tokens expire after one hour. If your app requires access after that time, it must request a refresh token by including duration=permanent

Later in the docs:

> App-only OAuth token requests never receive a refresh_token

They do not describe a remediation strategy for the missing refresh token. As a result I have assumed that the reason App-only OAuth doesn't receive a refresh token is because it does not require one and lasts indefinitely. This has been the case for the past few years at least, so I'm interested in the resolution to that thread.

**Comment by monkeydioude** [comment]
Exactly. I don't know if this Reddit post will have any effect, think we need to use a more official way.

I'll just try calling again the same access_token endpoint over and over again until then.
My people needs the spam or dank memes!

**Comment by Oshuma** [comment]
I'm having this issue also. Is there a known workaround in the meantime? Creating a new bot instance on a timer seems pretty hackish, but in theory it should work?

**Comment by monkeydioude** [comment]
@turnage I don't have the right to push a branch, so I forked your repo and made a MR. Can you review it ? 

https://github.com/turnage/graw/pull/53

Nothing's tested, I tried to go quick-and-not-so-dirty.

**Comment by SuprHackerSteve** [comment]
+1 

Also having this issue with Announcer stopping after 1 hour without any error.
