### ISSUE TITLE
"runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by seanvm** [turnage/graw#55]
Using the snippet provided in the doc for a logged out user (https://godoc.org/github.com/turnage/graw/reddit) I am getting the following error:
`"runtime error: invalid memory address or nil pointer dereference"` 

Link to the go sandbox with this error: https://play.golang.org/p/_UCIn3ClpzF

Any ideas whats wrong? I'm fairly new to Go so I'm hoping it is a simple mistake.

**Comment by turnage** [comment]
I would check the error values.

If err != nil, the value is nil and the error value should tell you why.

You are trying to use a value which is nil.

**Comment by seanvm** [comment]
@turnage thanks for responding so quickly. That was definitely my bad for not paying attention to the errors. 

The error that is being returned is `Get https://reddit.com/r/programming.json?raw_json=1: invalid request :path "r/programming.json?raw_json=1"` 

Is this path format not what I should be passing in? When making a regular http request outside of the graw package (e.g. `http.NewRequest("GET", "https://reddit.com/r/programming.json?raw_json=1", nil)`) it works...

**Comment by turnage** [comment]
That expects a permalink in the form of the “Permalink” field returned on
the reddit.Post type.

I wasn’t expecting it to be used with a string passed by hand so I’m not
sure of its exact syntax.

If you check and pass it in the right form, please consider making a PR
updating the comments on the Thread method to explain!
