### ISSUE TITLE
Get post that was just created

### ISSUE THREAD

**Issue by gastrodon** [turnage/graw#62]
Looking at method `reddit.Bot.PostLink` that just returns an error, I don't see an obvious way to create a post and then get an instance of that created post. Looking at the Reddit api docs for [submitting posts](https://www.reddit.com/dev/api/#POST_api_submit) it seems like that information is returned at post time.

Is there a way to get that information with this library?

**Comment by gastrodon** [comment]
This is something that I'd really like to see, so I started a [fork](https://github.com/gastrodon/graw). @turnage, are there any contributing guidelines I should follow? I did not see any in this repo

**Comment by turnage** [comment]
If you submit a pull request for this I will review it. Since people depend
on this package, this is what I think is important:

- That functionality has automated tests
- That API changes do not break existing code or change behavior in
existing code
- That commits are small and individually revertible where possible

Thank you for opening an issue and considering a contribution!

I think the hard part in adding this feature is figuring out how to extend
the API in a reasonable way.

**Comment by gastrodon** [comment]
I've added the functionality in what I think is a reasonable way. I made new methods `account.HarvestReply`, `account.HarvestSendMessage`, `account.HarvestPostSelf`, `account.HarvestPostLink` that behave like the ones they are based off of, but also return a new type `Submission` that represents a response to a submission of some kind. 

These methods use the new method `harvest_sow` that behaves in a similar way to sow, but instead will return a response that is parsed with a new parse method `parse_submitted`. I created a new parse method instead of using the existing `parse` because it did not look like that method was compatible with this returned data.

Existing tests pass, tests for these new methods have yet to be written. I'll probably do that in the following days, but if you'd like to peek at the fork to let me know if I'm heading in the right direction or if I'm missing something please do. Because of the way that this is implemented being different than what I assumed when I started the methods `Harvest*` and `harvest_sow` will probably be renamed`

**Comment by gastrodon** [comment]
oops

**Comment by turnage** [comment]
I've looked through the commits on your fork and I think it's mostly the right approach. If you open a pull request I'll review. Thank you for working on this!

**Comment by turnage** [comment]
Implemented in #64
