### ISSUE TITLE
500 status code when running the example

### ISSUE THREAD

**Issue by rakoo** [turnage/graw#75]
Hello,

I'm trying to run the example from [the book](https://turnage.gitbooks.io/graw/content/go.html), I have my own credentials, but when I run it I have a 500 error:

```
Failed to fetch /r/golang:  bad response code: 500
```

I don't even know where to start investigation, what caused it, what is the request, etc... Any idea how I can start digging into it ?

**Comment by turnage** [comment]
That code is coming from Reddit.

The requests are sent by this struct: https://github.com/turnage/graw/blob/master/reddit/client.go

Unless the tutorial has started failing for everyone, I suspect it has to do with the Reddit account.

**Comment by rakoo** [comment]
Sorry for troubling you. Reddit didn't recognize a character I was using in my app name (ĝ).

Thanks for the library it's really nice !

**Comment by turnage** [comment]
No worries! Vi devus peti Reddit efektivigi Esperanton.

**Comment by rakoo** [comment]
;)
