### ISSUE TITLE
Support the "more" return kind

### ISSUE THREAD

**Issue by wpwilson10** [turnage/graw#78]
I would like to be able to query /api/morechildren to get full comment trees from submissions. Currently there are functions like Lurker.Thread() or Scanner.ListingWithParams() on a submission link which get truncated comment trees. But I don't see a good way to get the full comment tree.

When using a Thread() call, there is a child with a "more" kind returned last in the list of comments, and it is being discarded from the comment list during parsing. This happens in parse.parseListing (since graw does not currently support the more type).

Here is an example of the raw json for this more kind from the children list of a Thread() call

{"kind": "more", "data": {"count": 1224, "name": "t1_fvand39", "id": "fvand39", "parent_id": "t3_hbo4a7", "depth": 0, "children": ["fvand39", ... "fvadr0f"]}}], "after": null, "before": null}}]

Or if there is an easier way to get the full comment tree from a submission like, I would love to know.

**Comment by wpwilson10** [comment]
I'm working on a pull request.

**Comment by Flexicon** [comment]
Issue can now be closed.
